### ISSUE TITLE
Webscrapping

### ISSUE THREAD

**Issue by anirudhajoshi2808** [BigDataIA-Spring2024-Sec1-Team4/Assignment2#1]
- [x] Extract 224 Webpages from CFA Link
- [x] The link to individual 224 webpages is dynamic (not included in source code): Find a way for extraction
- [x] Storing the scrapped data in CSV file format (Extraction of pdf link and webpage link, other details are straightforward)

**Comment by NitantJatale** [comment]
WebScrapping Success

**Comment by anirudhajoshi2808** [comment]
To be revised during Airflow orchestration
